### ISSUE TITLE
404 for riderStatus

### ISSUE THREAD

**Issue by otakuu** [Ogadai/zwift-mobile-api#10]
Hi, 

When I wanna get the riderStatus I get a 404:

world.riderStatus(playerId).then(status => {
    console.log(status); // JSON of rider status
});

**(node:12596) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Request failed with status code 404**

**Comment by otakuu** [comment]
i am an idiot. rider has to be riding...

**Comment by Ogadai** [comment]
No worries @otakuu - it's not obvious and probably should be mentioned in the docs :-)

**Comment by otakuu** [comment]
hi ogadai

your API is awesome! thank you for this work!

i wanna build a speed controlled fan like you and i saw your project. would
you mind sending me a skeleton of settings.js. It's git-ignored.

greets
domnic

2017-11-30 10:20 GMT+01:00 Ogadai <notifications@github.com>:

**Comment by Ogadai** [comment]
I think you're referring to the [zwift-fan-speed](https://github.com/Ogadai/zwift-fan-speed) project?

`settings.js` is ignored because it has credentials in it. It should look something like this:

```
module.exports = {
    username: '{zwift user name}',
    password: '{zwift password}',
    player: {zwift rider id},
    interval: 2000,
    fan: {
        gpio: { pin: 20 },
        min: 10,
        max: 50,
        scale: 1.5,
        pollInterval: 20
    }
};
```

Note that this project works with my 12v DC fan (turning the power off and on to slow it down). A mains/AC fan would require a different approach (and [not a dimmer switch](https://www.facebook.com/groups/zwiftCoders/permalink/1215919811873577/))

**Comment by otakuu** [comment]
thank you very much!

2017-11-30 14:10 GMT+01:00 Ogadai <notifications@github.com>:
